apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260609-224621-vk9p81jgplt3-service
spec:
  selector:
    app: enterprise-system-20260609-224621-vk9p81jgplt3
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
